const TOOL_ROUTE_MAP = {
  merge: 'merge-pdf',
  split: 'split-pdf',
  extract: 'extract-pages-from-pdf',
  remove: 'remove-pages-from-pdf',
  reorder: 'organize-pdf',
  compress: 'compress-pdf',
  repair: 'repair-pdf',
  ocr: 'ocr-pdf',
  img2pdf: 'jpg-to-pdf',
  word2pdf: 'word-to-pdf',
  excel2pdf: 'excel-to-pdf',
  ppt2pdf: 'powerpoint-to-pdf',
  html2pdf: 'html-to-pdf',
  pdf2img: 'pdf-to-jpg',
  pdf2word: 'pdf-to-word',
  pdf2excel: 'pdf-to-excel',
  pdf2ppt: 'pdf-to-powerpoint',
  pdf2pdfa: 'pdf-to-pdfa',
  editor: 'edit-pdf',
  rotate: 'rotate-pdf',
  watermark: 'watermark-pdf',
  pagenums: 'add-page-numbers-to-pdf',
  crop: 'crop-pdf',
  unlock: 'unlock-pdf',
  protect: 'protect-pdf',
  sign: 'sign-pdf',
  redact: 'redact-pdf',
  compare: 'compare-pdf',
  translate: 'translate-pdf',
  summarize: 'summarize-pdf',
};

const LANDING_ROUTE_SLUGS = [
  'compress-pdf-to-1mb',
  'compress-pdf-to-500kb',
  'merge-pdf-without-watermark',
  'pdf-to-word-editable',
  'scan-pdf-to-searchable-pdf',
  'compress-pdf-for-email',
  'compress-pdf-without-losing-quality',
  'pdf-to-word-free',
  'pdf-to-jpg-high-quality',
  'word-to-pdf-online-free',
  'edit-pdf-text-online',
  'sign-pdf-online-free',
  'protect-pdf-with-password',
  'extract-pages-from-pdf-online',
  'remove-pages-from-pdf-online',
];

module.exports = {
  TOOL_ROUTE_MAP,
  LANDING_ROUTE_SLUGS,
};